re-install node modules to avoid error while build
```console
$ npm run build

> transform-matrix@0.1.0 build /mnt/c/Users/ginpei/projects/transform-matrix
> vue-cli-service build

⠋  Building for production... ERROR  Error: Cannot find module './lib/convert'
Error: Cannot find module './lib/convert'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/mnt/c/Users/ginpei/projects/transform-matrix/node_modules/postcss-convert-values/dist/index.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! transform-matrix@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the transform-matrix@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ginpei/.npm/_logs/2018-11-11T23_38_08_880Z-debug.log
```